#!/bin/sh
if git diff --name-only HEAD@{1} HEAD | grep -q "package.json\|pnpm-lock.yaml\|yarn.lock\|package-lock.json"; then
  echo "📦 Dependências mudaram, instalando pacotes..."
  npm install
else
  echo "✅ Nenhuma mudança em dependências."
fi

echo "🔍 Executando npm audit..."
npm audit || { echo "Erro durante o npm audit. Continuando..."; }